name: Metrics
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * MON'
  workflow_dispatch:
      inputs:
      name:
        description: 'Start Metrics Workflow'
        required: true
        default: 'Metrics for Zakon Technomantów'    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: zakon-technomantow
          token: ${{ secrets.METRICS_TOKEN }} 
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Warsaw
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_visibility: all
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_threshold: 0%
          plugin_lines: yes
          repositories_forks: yes 
          repositories_affiliations: ""
